import { useState, useEffect } from 'react';
import {
  Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  BarChart, Bar, AreaChart, Area
} from 'recharts';
import { Zap, Settings, BarChart3, Activity, Battery, TrendingUp, AlertCircle, Sun } from 'lucide-react';

// --- Types ---
type UserRole = 'GUEST' | 'ADMIN';
type BotAction = 'IDLE' | 'CHARGE' | 'DISCHARGE';

interface PricePoint {
  time: string;
  price: number;
  action: BotAction;
  soc: number;
}

interface DailyStat {
  day: string;
  profit: number;
  solarCheck: number;
}

// --- Data Generator ---
const generateDayData = (): PricePoint[] => {
  const data: PricePoint[] = [];
  let currentSoc = 50;

  for (let i = 0; i < 24; i++) {
    // Duck Curve Simulation (High morning/evening, low midday)
    const base = 50;
    const curve = Math.sin((i - 6) * 0.5) * 40; // Peak morning/evening
    const solarDip = (i > 9 && i < 17) ? -60 : 0; // Solar dip
    let price = Math.max(0, base + curve + solarDip + (Math.random() * 10));

    // Logic simulation
    let action: BotAction = 'IDLE';
    if (price < 40 && currentSoc < 90) {
      action = 'CHARGE';
      currentSoc += 15;
    } else if (price > 90 && currentSoc > 20) {
      action = 'DISCHARGE';
      currentSoc -= 15;
    }

    currentSoc = Math.min(100, Math.max(20, currentSoc));

    data.push({
      time: `${i}:00`,
      price: Math.floor(price),
      action,
      soc: Math.floor(currentSoc)
    });
  }
  return data;
};

const generateMonthData = (): DailyStat[] => {
  return Array.from({ length: 30 }, (_, i) => ({
    day: `Jan ${i + 1}`,
    profit: Math.floor(Math.random() * 15) + 5, // 5-20 EUR per day
    solarCheck: Math.floor(Math.random() * 100)
  }));
};

// --- Components ---
const StatCard = ({ title, value, unit, icon: Icon, color }: any) => (
  <div className="glass-card p-6 flex items-center justify-between">
    <div>
      <p className="text-slate-400 text-sm font-medium uppercase tracking-wider">{title}</p>
      <div className="flex items-baseline gap-1 mt-2">
        <span className="text-3xl font-bold text-slate-100 neon-text">{value}</span>
        <span className="text-slate-500 text-sm">{unit}</span>
      </div>
    </div>
    <div className={`p-3 rounded-xl bg-${color}-500/10 text-${color}-400`}>
      <Icon size={24} />
    </div>
  </div>
);

function App() {
  const [role, setRole] = useState<UserRole>('GUEST');
  const [data, setData] = useState<PricePoint[]>([]);
  const [history, setHistory] = useState<DailyStat[]>([]);
  const [password, setPassword] = useState('');
  const [timeIndex, setTimeIndex] = useState(0);

  // Init Data from JSON (Generated by Python Action)
  useEffect(() => {
    // 1. Load History (Static Mock for now)
    setHistory(generateMonthData());

    // 2. Fetch "Live" Data
    fetch('./data/omie_live.json')
      .then(res => res.json())
      .then(jsonData => {
        setData(jsonData.data);
      })
      .catch(err => {
        console.error("Failed to load live data, falling back to simulation", err);
        setData(generateDayData());
      });
  }, []);

  // Timer
  useEffect(() => {
    const timer = setInterval(() => {
      setTimeIndex((prev) => (prev + 1) % 24);
    }, 2000); // 2s per hour
    return () => clearInterval(timer);
  }, []);

  const current = data[timeIndex] || { price: 0, soc: 0, action: 'IDLE' };
  const getActionColor = (a: BotAction) => {
    if (a === 'CHARGE') return 'text-green-400';
    if (a === 'DISCHARGE') return 'text-orange-400';
    return 'text-slate-500';
  };

  return (
    <div className="min-h-screen p-6 md:p-12 text-slate-200">

      {/* Header */}
      <header className="max-w-7xl mx-auto mb-12 flex justify-between items-center glass-card p-4">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 bg-blue-600 rounded-lg flex items-center justify-center text-white font-bold text-xl shadow-lg shadow-blue-500/50">
            JB
          </div>
          <div>
            <h1 className="text-2xl font-bold bg-gradient-to-r from-blue-400 to-cyan-300 bg-clip-text text-transparent">
              JB-Enterprise Victron Pilot
            </h1>
            <div className="flex items-center gap-2">
              <span className="relative flex h-3 w-3">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
                <span className="relative inline-flex rounded-full h-3 w-3 bg-green-500"></span>
              </span>
              <p className="text-xs text-green-400 font-mono tracking-wide">CERBO GX ONLINE • PORTUGAL (OMIE)</p>
            </div>
          </div>
        </div>

        {role === 'GUEST' ? (
          <div className="flex gap-2">
            <input
              type="password"
              placeholder="Admin PIN"
              className="bg-slate-800 border border-slate-700 rounded px-3 py-1 text-sm focus:outline-none focus:border-blue-500 transition-colors"
              onChange={(e) => setPassword(e.target.value)}
            />
            <button
              onClick={() => password === 'admin123' && setRole('ADMIN')}
              className="bg-blue-600 hover:bg-blue-500 px-4 py-1 rounded text-sm font-medium transition-all"
            >
              Unlock
            </button>
          </div>
        ) : (
          <span className="px-3 py-1 bg-red-500/20 text-red-400 rounded border border-red-500/50 text-xs font-bold uppercase">
            Admin Mode Type 2
          </span>
        )}
      </header>

      <main className="max-w-7xl mx-auto space-y-8">

        {/* KPI Grid */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          <StatCard
            title="Real-Time Price"
            value={current.price}
            unit="€/MWh"
            icon={TrendingUp}
            color="blue"
          />
          <StatCard
            title="Battery State"
            value={current.soc}
            unit="%"
            icon={Battery}
            color={current.soc < 30 ? 'red' : 'green'}
          />
          <StatCard
            title="Bot Action"
            value={current.action}
            unit=""
            icon={Activity}
            color="purple"
          />
          <StatCard
            title="Est. 30-Day Profit"
            value="342"
            unit="€"
            icon={Sun}
            color="yellow"
          />
        </div>

        {/* Charts Section */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">

          {/* Main Chart (Live) */}
          <div className="lg:col-span-2 glass-card p-6">
            <h3 className="text-lg font-semibold mb-6 flex items-center gap-2">
              <BarChart3 className="text-blue-400" />
              Live Market Tracking (24h)
            </h3>
            <div className="h-[350px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={data}>
                  <defs>
                    <linearGradient id="colorPrice" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.3} />
                      <stop offset="95%" stopColor="#3b82f6" stopOpacity={0} />
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} />
                  <XAxis dataKey="time" stroke="#94a3b8" fontSize={12} tickLine={false} />
                  <YAxis stroke="#94a3b8" fontSize={12} tickFormatter={(val) => `€${val}`} tickLine={false} />
                  <Tooltip
                    contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155', color: '#f8fafc' }}
                    itemStyle={{ color: '#cbd5e1' }}
                  />
                  <Area
                    type="monotone"
                    dataKey="price"
                    stroke="#3b82f6"
                    strokeWidth={3}
                    fillOpacity={1}
                    fill="url(#colorPrice)"
                    name="OMIE Price"
                  />
                  <Line
                    type="step"
                    dataKey="soc"
                    stroke="#22c55e"
                    strokeWidth={2}
                    dot={false}
                    name="Battery SoC"
                  />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Side Panel (Controls or History) */}
          <div className="space-y-6">

            {/* Simulation Clock */}
            <div className="glass-card p-6 bg-blue-600/10 border-blue-500/30">
              <div className="flex justify-between items-center mb-2">
                <span className="text-xs uppercase text-blue-300 font-bold tracking-widest">Simulated Time</span>
                <Zap size={16} className="text-yellow-400 animate-pulse" />
              </div>
              <div className="text-4xl font-mono font-bold text-white tracking-tighter">
                {current.time}
              </div>
              <div className="mt-4 flex items-center gap-2">
                <span className={`text-sm font-bold uppercase px-3 py-1 rounded-full bg-black/30 border border-white/10 ${getActionColor(current.action)}`}>
                  {current.action}
                </span>
                <span className="text-xs text-slate-400">Current Strategy Mode</span>
              </div>
            </div>

            {/* Admin Controls */}
            {role === 'ADMIN' && (
              <div className="glass-card p-6 border-red-500/20">
                <h3 className="text-sm font-bold text-red-400 uppercase tracking-widest mb-4 flex items-center gap-2">
                  <Settings size={16} /> Manual Override
                </h3>
                <div className="grid grid-cols-2 gap-3">
                  <button className="bg-red-500/10 hover:bg-red-500/20 border border-red-500/30 text-red-400 py-3 rounded text-sm font-bold transition-all">
                    FORCE CHARGE
                  </button>
                  <button className="bg-orange-500/10 hover:bg-orange-500/20 border border-orange-500/30 text-orange-400 py-3 rounded text-sm font-bold transition-all">
                    DUMP TO GRID
                  </button>
                </div>
                <div className="mt-4 p-3 bg-red-900/20 rounded border border-red-900/30 flex items-start gap-2">
                  <AlertCircle size={16} className="text-red-400 shrink-0 mt-0.5" />
                  <p className="text-xs text-red-300 leading-relaxed">
                    Override will bypass price logic for 60 minutes. Use caution.
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Historical Data Section */}
        <div className="glass-card p-6">
          <h3 className="text-lg font-semibold mb-6 text-slate-200">30-Day Performance Audit</h3>
          <div className="h-[250px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={history}>
                <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} />
                <XAxis dataKey="day" stroke="#64748b" fontSize={10} tickLine={false} interval={2} />
                <Tooltip
                  cursor={{ fill: '#334155', opacity: 0.4 }}
                  contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155', color: '#f8fafc' }}
                />
                <Bar dataKey="profit" fill="#3b82f6" radius={[4, 4, 0, 0]} name="Daily Profit (€)" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

      </main>
    </div>
  );
}

export default App;
